### ISSUE TITLE
[Questions] Move up/down through the hierarhy

### ISSUE THREAD

**Issue by mskorzhinskiy** [publicimageltd/lister#3]
I am a user of the delve and since delve mode is built with the help of lister, it seems to me that this is the right place to ask the question.

How could I add a keybinding to move up/down through the hierarchy? In the org-mode and the outline mode there a keybinding to move to the parent or move to the first child. Also there are keybindings to move to the next/previous siblings, omitting children.

Is it possible to do the same functions? Would you be interested to add them to this library?

**Comment by publicimageltd** [comment]
Thanks for that suggestion! I like the idea. It's not difficult to implement, I'll do it. What functions (which what key bindings) are we talking about exactly? I'd say the following:

1. Move up / down one item on the same level (skipping any more deeply nested children)
2. Move up to parent node
3. Move up to first child (that is, move to parent node, unfold children, go to first child)
4. Move down to first children (does that make sense? I can't imagine a usecase)

As to the binding, my suggestion is:

1. Move up/down on the same level -> C-c C-f  / C-c C-b (like in Org-Mode: Foward heading same level)
2. Move to parent -> C-c C-u (= keybinding of `outline-up-parent)
3. Move to first children below parent: M-<
4. Move to last childen below parent: M->
5. Move to first children (one level deeper than the current):  ??

All keybindings will be added to `lister-mode`. I will try to integrate the cases 3. and 4. using the wonderful `beginend` package. It allows these keybindings to be used multiple times with different meaning:  pressing M-< moves to the first children of the current level, and pressing it the second time would then move forward to the beginning of the list. Of course, only as an optional dependency, the user can bind the functions in whatever way they choose.

What do you think?

**Comment by mskorzhinskiy** [comment]
> Move up / down one item on the same level (skipping any more deeply nested children)

Definitely yes.

 > Move up to parent node

Definitely yes. (e.g. imagine very long list and you want to jump to the parent for faster navigation)

> Move up to first child (that is, move to parent node, unfold children, go to first child)
> Move down to first children (does that make sense? I can't imagine a usecase)

For the interactive function the second choice doesn't have a usecase, I agree. However for some kind of programming / making your own navigation functions, would be great if some kind of basic "go to first child" would exist.

> As to the binding, my suggestion is:

Unfortunately I am evil user at the moment, so I'm not sure if my taste could be useful here. And also I will be using different keybindings anyway. But these keybindings sound reasonable to me.

> What do you think?

Thank you very much for your efforts and the hard work! Very much appreciated. Let me know I could help you anyhow.

**Comment by publicimageltd** [comment]
Re "helping": Well, you could help me by providing some useful keybinding for evil -- maybe even for all functions of `lister-mode`? I imagine setting some switch which will enable the evil keymap if evil-mode is active, or something like that. Many people seem to use it, so that should be worthwhile.

**Comment by publicimageltd** [comment]
Done. See the README for the new keybindings, they are all part of `lister-mode`. Please report any bugs or issues you experience!
