### ISSUE TITLE
Disable View-mode

### ISSUE THREAD

**Issue by meedstrom** [publicimageltd/lister#4]
Hi! Found a problem and a fix:  some people (like me) have `view-read-only` t.  In this situation, a few keys in `lister-mode-map` get lost, such as m for mark and u for unmark.

To fix, you could add the function `View-exit` as a preexisting hook on `lister-mode-hook`.

**Comment by publicimageltd** [comment]
A precise proposal which I will implement soonish. Thanks!

**Comment by publicimageltd** [comment]
Should be it.
