### ISSUE TITLE
How to promote or demote an item and its sublist

### ISSUE THREAD

**Issue by msingh15-tufts** [publicimageltd/lister#5]
Thanks for creating this package. It will really help in creating interesting UIs with nested lists. I have a question about the following:
Lets say I have the following list:
```
A
- B
- C
- - D
- - E

```
And I want to promote C and its items, such that the structure results in:
```
A
- B
C
- D
- E

```
Do the current interactive lister-move functions allow for this? Do you have a suggestion for how to add this?

**Comment by publicimageltd** [comment]
Is that what you need?

```emacs-lisp
(let ((ewoc (lister-setup "test" (apply-partially #'format "%s"))))
  (lister-set-list ewoc '("A" ("B" "C" ("D" "E"))))
  ;; fn to decrease level by 1
  (cl-labels ((dedent (e n) (lister-set-node-level e n
                                                   (1- (lister-node-get-level n)))))
    ;; identify top node
    (let ((top-node (lister-get-node-at ewoc 2)))
      ;; a "sublist" is all nodes with same level below the top node
      (lister-with-sublist-below ewoc top-node beg end
        ;; dedent the sublist
        (lister-walk-nodes ewoc #'dedent beg end)
        ;; and the top node
        (dedent ewoc top-node)))))
    
```

Feel free to wrap that in more general function and make a PR. It's a good idea actually to have that at hand.

**Comment by publicimageltd** [comment]
Ups I just saw that it already has a function `lister-move-sublist...` (which you allude to). Has been a long time I did something in that code..

**Comment by publicimageltd** [comment]
So here's the updated snippet:

```emacs-lisp
(let ((ewoc (lister-setup "test" (apply-partially #'format "%s"))))
  (lister-set-list ewoc '("A" ("B" "C" ("D" "E" ("F") "G"))))
  (let* ((top-node (lister-get-node-at ewoc 2))
         (level    (lister-get-level-at ewoc top-node)))
    (lister-move-sublist-left ewoc (ewoc-next ewoc top-node))
    (lister-set-level-at ewoc top-node (1- level)))) 
```

The "trick" is to dedent the top-node manually, which is not handled by lister-move-sublist-left. 

Note that in an interactive funciton, you must check on level (eq 0) if you want to handle this case gracefully. Check ideally before calling move-sublist-left. The move function throws an unspecific user error. I admit that is not good design :-)

**Comment by msingh15-tufts** [comment]
I thought of doing something similar to what you suggest, but I think things would get very complex if there are multiple levels below my current level. 

Ideally, there would be a function to move a node and all its subnodes (and their subnodes) left or right.

I suspect I'll try to solve this in the future. For now, I just recreate the whole tree when I need to make moves like above.

**Comment by publicimageltd** [comment]
The last snippet should work fine with multiple nested levels. The move function handles sublevels corrrectly. If you can isolate an example where it does not work, open another issue.

Am 5. August 2024 02:47:59 MESZ schrieb msingh15-tufts ***@***.***>:

**Comment by msingh15-tufts** [comment]
Thanks! I was doing other things wrong.

Similar question to above, how would you suggest I move items up and down while keep their sublists:
`
- A
- - B
- C
- - D
- E
`
to
`
- C
- - D
- A
- - B
- E
`
Here my question is for both situations, either moving (A (B)) down or moving (C (D)) up.

Sorry for asking these questions, I've tried solving this for the last 2 hours and I am not succeeding in consistently moving A item and its list up and down without messing the heirarchy of something in whole list.

Any suggestions by you are very appreciated!

**Comment by publicimageltd** [comment]
Use `lister-move-sublist-down` resp. `....-up`. The argument POS is the first element of the list to be moved. It identifies the sublist by indentation (that is, the sublist extends to every item which has the same or a bigger indentation than the item at POS) and moves it up or down as you want it.

**Comment by publicimageltd** [comment]
I am not testing it now, there should be no trick here. Moving left/right needs a manual 'dedent' due to the logical problem that in that case, you cannot identify a sublist easily (the item at pos actually *becomes* a sublist after moving). In the case of up/down, the item at point already *is* a sublist, so everything should work fine.
